# Generated by Django 2.2.6 on 2019-10-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(max_length=10)),
                ('lecture', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=10)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=5)),
            ],
        ),
    ]
