# Generated by Django 2.2.6 on 2019-10-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
